- name: Install packages on Debian-based systems
  apt:
    name:
      - curl
      - wget
      - git
      - btop
      - nmap
      - gobuster
      - tmux
      - neovim
      - docker.io
    state: present
    update_cache: yes

